spring:
  #jackson:
  #  serialization:
  #    fail-on-empty-beans: false
  cache:
    type: simple
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Nupur@29
    # JPA properties
  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 353930203289-clf9o86au4r4q7jkii425u1jtl7k9g9j.apps.googleusercontent.com
            client-secret: tnT5UJuQyBvjFP6Hdut0sU4f

